name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ["65.1.145.241"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ matrix.host }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/app
            git pull origin main
            pm2 restart all
